server:
  port: 9002
spring:
  application:
    name: eureka-server
eureka:
  client:
    #声明是否将自己的注册信息注册到Eureka服务器
    register-with-eureka: true
    #fetch-registry 表示是否到Eureka服务器中抓取注册信息
    fetch-registry: true
    #添加注册地址，多个用逗号拼接
    service-url:
      defaultZone: http://clear01:9001/eureka/
  instance:
    hostname: clear02